### ISSUE TITLE
Great idea. Unfortunately the game is incomplete.

### ISSUE THREAD

**Issue by TaurusOlson** [maebert/shellcraft#7]
* ShellCraft version: 0.9.4
* Python version: 3.5.1
* Operating System: Debian GNU/Linux 9.4 (stretch) x86_64

### Description

Hello maebert,
I really like the concept this game and the concepts. However it seems the most interesting part is missing. For example, I managed to research the dynamite but can't craft it. I saw the Names and the Epithets were implemented but there's no way to interact with them. 

Do you plan to continue this game? I think it has a lot of potential.

**Comment by maebert** [comment]
Hi Taurus, thanks for finding this game!

It is definitely incomplete, and since I started a new job I had very little time to work on it. If you want to play around with the concepts for Names and Epithets you can check out the [automata](https://github.com/maebert/shellcraft/tree/automata) branch. And if you're interested in joining the development and driving the game forward, let me know :)
